version: 0.2

env:
  variables:
    REPORT_BUCKET: $REPORT_BUCKET

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - npx cypress verify

  pre_build:
    commands:
      - echo "Setting BASE URL for Cypress..."
      - echo "Base URL:$CYPRESS_BASE_URL"
      - export XDG_RUNTIME_DIR=/tmp/runtime-$UID
      - mkdir -p $XDG_RUNTIME_DIR
      - chmod 700 $XDG_RUNTIME_DIR

  build:
    commands:
      - echo "Preparing Cypress folders..."
      - mkdir -p cypress/videos cypress/screenshots cypress/results
      - echo "Running Cypress tests..."
      - npx cypress run --browser chrome --config baseUrl=$CYPRESS_BASE_URL
      - echo "Listing files for debugging"
      - find cypress -type f || true
      - mkdir -p cypress_artifacts
      - cp -r cypress/videos cypress/screenshots cypress/results cypress_artifacts/

  post_build:
    commands:
      - echo "Uploading test report artifacts to S3 bucket..."
      - export ZIP_NAME="report-$(date +%Y-%m-%d_%H-%M-%S).zip"
      - zip -r $ZIP_NAME cypress_artifacts/*
      - aws s3 cp $ZIP_NAME s3://$REPORT_BUCKET/
      - echo "Upload complete: $ZIP_NAME"

artifacts:
  files:
    - cypress_artifacts/**/*


